SET IDENTITY_INSERT [dbo].[VehicleBrand] ON
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (1, N'Holden')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (2, N'Ford')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (3, N'Ferrari')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (4, N'Porsche')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (5, N'Toyota')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (6, N'Chevrolet')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (7, N'BMW')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (8, N'Audi')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (9, N'Hyundai')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (10, N'Honda')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (11, N'Volkswagen')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (12, N'Nissan')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (13, N'Kia')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (14, N'Jeep')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (15, N'Tesla')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (16, N'Land Rover')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (17, N'Mercedes-Benz')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (18, N'Volvo')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (19, N'Jaguar')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (20, N'Fiat')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (21, N'Mazda')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (22, N'Subaru')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (23, N'Suzuki')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (24, N'Lexus')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (25, N'Aston Martin')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (26, N'Mitsubishi')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (27, N'Peugeot')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (28, N'Seat')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (29, N'Bugatti')
INSERT INTO [dbo].[VehicleBrand] ([BrandId], [BrandName]) VALUES (30, N'Lamborghini')
SET IDENTITY_INSERT [dbo].[VehicleBrand] OFF
