SET IDENTITY_INSERT [dbo].[Fault] ON
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (1, N'Brake Pad Failure', 1, 1)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (2, N'Engine Overheating', 2, 2)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (3, N'Air Filter Blockage', 3, 3)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (4, N'Oil Leak', 4, 4)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (5, N'Battery Failure', 5, 5)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (6, N'Headlight Malfunction', 6, 6)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (7, N'Tail Light Out', 7, 7)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (8, N'Spark Plug Issue', 8, 8)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (9, N'Radiator Leak', 9, 9)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (10, N'Fuel Pump Failure', 10, 10)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (11, N'Water Pump Failure', 11, 11)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (12, N'Clutch Slippage', 12, 12)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (13, N'Transmission Problem', 13, 13)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (14, N'Window Motor Failure', 14, 14)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (15, N'Door Handle Issue', 15, 15)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (16, N'Ignition Coil Fault', 16, 16)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (17, N'Stimulator Fault', 17, 17)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (18, N'Wheel Bearing Noise', 18, 18)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (19, N'Sway Bar Link Damage', 19, 19)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (20, N'Control Arm Wear', 20, 20)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (21, N'Ball Joint Issue', 21, 21)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (22, N'Strut Failure', 22, 22)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (23, N'Spring Damage', 23, 23)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (24, N'Fuel Filter Blockage', 24, 24)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (25, N'Fuse Failure', 25, 25)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (26, N'Cooling Fan Failure', 26, 26)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (27, N'Hubcap Loss', 27, 27)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (28, N'Brake Rotor Wear', 28, 28)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (29, N'Cabin Filter Blockage', 29, 29)
INSERT INTO [dbo].[Fault] ([FaultId], [FaultName], [VehicleId], [CustomerId]) VALUES (30, N'General Engine Issue', 30, 30)
SET IDENTITY_INSERT [dbo].[Fault] OFF