SET IDENTITY_INSERT [dbo].[VehicleModel] ON
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (1, N'Colorado', 1)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (2, N'Commodore', 1)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (3, N'Astra', 1)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (4, N'Mustang', 2)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (5, N'Focus', 2)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (6, N'F-150', 2)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (7, N'488 Spider', 3)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (8, N'F8 Tributo', 3)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (9, N'Roma', 3)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (10, N'911', 4)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (11, N'Cayenne', 4)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (12, N'Macan', 4)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (13, N'Corolla', 5)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (14, N'Camry', 5)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (15, N'RAV4', 5)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (16, N'Silverado', 6)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (17, N'Equinox', 6)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (18, N'Malibu', 6)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (19, N'3 Series', 7)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (20, N'X5', 7)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (21, N'M3', 7)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (22, N'A4', 8)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (23, N'Q7', 8)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (24, N'R8', 8)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (25, N'Elantra', 9)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (26, N'Santa Fe', 9)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (27, N'Kona', 9)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (28, N'Accord', 10)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (29, N'CR-V', 10)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (30, N'Civic', 10)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (31, N'Golf', 11)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (32, N'Tiguan', 11)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (33, N'Passat', 11)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (34, N'Altima', 12)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (35, N'Rogue', 12)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (36, N'Leaf', 12)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (37, N'Optima', 13)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (38, N'Sportage', 13)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (39, N'Sorento', 13)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (40, N'Wrangler', 14)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (41, N'Cherokee', 14)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (42, N'Grand Cherokee', 14)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (43, N'Model S', 15)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (44, N'Model 3', 15)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (45, N'Model X', 15)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (46, N'Defender', 16)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (47, N'Range Rover', 16)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (48, N'Discovery', 16)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (49, N'C-Class', 17)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (50, N'E-Class', 17)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (51, N'S-Class', 17)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (52, N'XC90', 18)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (53, N'S60', 18)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (54, N'V90', 18)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (55, N'F-PACE', 19)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (56, N'XE', 19)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (57, N'XF', 19)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (58, N'500', 20)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (59, N'Panda', 20)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (60, N'Tipo', 20)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (61, N'CX-5', 21)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (62, N'Mazda3', 21)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (63, N'MX-5 Miata', 21)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (64, N'Outback', 22)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (65, N'Impreza', 22)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (66, N'Forester', 22)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (67, N'Swift', 23)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (68, N'Vitara', 23)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (69, N'Jimny', 23)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (70, N'RX', 24)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (71, N'ES', 24)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (72, N'NX', 24)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (73, N'DB11', 25)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (74, N'Vantage', 25)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (75, N'DBS', 25)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (76, N'Outlander', 26)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (77, N'Lancer', 26)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (78, N'Triton', 26)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (79, N'208', 27)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (80, N'3008', 27)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (81, N'5008', 27)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (82, N'Leon', 28)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (83, N'Ateca', 28)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (84, N'Ibiza', 28)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (85, N'Chiron', 29)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (86, N'Veyron', 29)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (87, N'Divo', 29)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (88, N'Huracan', 30)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (89, N'Aventador', 30)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (90, N'Urus', 30)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (91, N'1 Series', 7)
INSERT INTO [dbo].[VehicleModel] ([ModelId], [ModelName], [BrandId]) VALUES (92, N'Aqua', 5)
SET IDENTITY_INSERT [dbo].[VehicleModel] OFF