using System.ComponentModel.DataAnnotations;
using System.Numerics;

namespace KollamAutoEng_web.Models
{
    // Enum to represent the status of an employee (either Active or Inactive)
    public enum Status
    {
        Active, Inactive
    }

    // Employee class representing the employee details
    public class Employee
    {
        // Primary key for the Employee entity, automatically generated by the database
        [Key] // Indicates that this is the primary key
        [Display(Name = "Employee ID")] // Specifies how the field will be labeled in the UI
        public int EmployeeId { get; set; }

        // Employee's first name - required field with minimum and maximum length constraints
        [Required(ErrorMessage = "Please enter Employee First Name")] // Ensures first name is mandatory
        [MinLength(3)] // Ensures the name has a minimum of 3 characters
        [MaxLength(25)] // Ensures the name has a maximum of 25 characters
        [RegularExpression(@"^([A-Z][a-z]+)(\s[A-Z][a-z]+)*$", ErrorMessage = "Each word must start with a capital letter, and only letters and single spaces are allowed.")]
        // Ensures that the first letter of each word is capitalized and that only letters and single spaces are allowed
        [Display(Name = "First Name")] // Display name for FirstName in views
        public string FirstName { get; set; }

        // Employee's last name - required field with minimum and maximum length constraints
        [Required(ErrorMessage = "Please enter Employee Last Name")] // Ensures last name is mandatory
        [MinLength(3)] // Ensures the last name has a minimum of 3 characters
        [MaxLength(25)] // Ensures the last name has a maximum of 25 characters
        [RegularExpression(@"^([A-Z][a-z]+)(\s[A-Z][a-z]+)*$", ErrorMessage = "Each word must start with a capital letter, and only letters and single spaces are allowed.")]
        // Ensures that each word in the last name starts with a capital letter, followed by lowercase letters, and only letters and single spaces are allowed
        [Display(Name = "Last Name")] // Display name for LastName in views
        public string LastName { get; set; }

        // Employee's phone number - validated with custom phone number format rules for New Zealand and India
        [Required]
        [DataType(DataType.PhoneNumber), MaxLength(17)] // Specifies that this is a phone number field, with a maximum length of 17 characters
        [RegularExpression(@"^\+((64 (\b(2[0-6])\b)-\d{3,4}-\d{4,5})|(91 \d{5}-\d{5}))$",
        ErrorMessage = "Phone Number is not valid.\n\n" +
               "For New Zealand:\n" +
               "+64 followed by a 2-digit area code (20-26),\n" +
               "a 3- or 4-digit local number,\n" +
               "and a 4- or 5-digit subscriber number.\n" +
               "(e.g., +64 20-345-6789 or +64 22-1234-5678).\n\n" +
               "For India:\n" +
               "+91 followed by two groups of 5 digits separated by a hyphen.\n" +
               "(e.g., +91 75920-12345).")]
        // Validates phone number format for New Zealand and India
        [Display(Name = "Phone Number")] // Display name for PhoneNumber in views
        public string PhoneNumber { get; set; }

        // Employee's status (Active or Inactive)
        [Display(Name = "Status")] // Display name in UI
        public Status? Status { get; set; }

        // Employee's pay - required, validated as a currency, and restricted to a valid range
        [DataType(DataType.Currency)] // Specifies that the field should be treated as a currency value
        [Required(ErrorMessage = "Please enter Employee Pay")] // Field is mandatory
        [RegularExpression(@"^(0|[1-9][0-9]{0,4}(,[0-9]{3})*)(\.[0-9]{1,2})?$", ErrorMessage = "Please enter a valid positive number (e.g., 1,000 or 1000).")]
        // This regex allows numbers with optional commas as thousands separators and decimals with up to 2 places.
        [Range(0.99, 1000, ErrorMessage = "Please enter a value between 0.99 and 1,000.")]
        [Display(Name = "Pay")] // Display label for UI
        public decimal Pay { get; set; }

        // Employee's working hours - required, must fall within a specified range, and allows up to two decimal places
        [Required(ErrorMessage = "Please enter Employee Hours")] // Field must be filled out
        [Range(1, 144, ErrorMessage = "Please enter a value between 1 and 144 hours.")] // Ensures hours fall within the range 1 to 144
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Please enter a valid decimal value with up to two decimal places.")] // Ensures the input is a valid decimal with up to 2 decimal places
        [Display(Name = "Hours")] // Display name in UI
        public decimal Hours { get; set; }

        // A collection of appointments associated with the employee (optional)
        public virtual ICollection<Appointment>? Appointments { get; set; } // Navigational property for related appointments
    }
}
